default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :preview do
    sh("cd .. && xcodegen generate")
    
    increment_build_number(xcodeproj: "#{ENV['APP_NAME']}.xcodeproj")
    
    build_app(scheme: ENV['APP_NAME'])

    api_key_path = File.exist?("AuthKey.json") ? "fastlane/AuthKey.json" : "fastlane/AuthKey.p8"
    
    upload_to_testflight(
      api_key_path: api_key_path,
      skip_waiting_for_build_processing: true
    )
  end
end
